import hero from "../../assets/hero.png";
export default function Landing() {
  return (
    <div
      id="about"
      className="lg:grid lg:grid-cols-12 lg:gap-8 py-20 items-center"
    >
      <div className="sm:text-center md:max-w-2xl md:mx-auto lg:col-span-4 lg:text-left">
        <h1>
          <span className="mt-1 block text-4xl tracking-tight font-extrabold sm:text-5xl xl:text-6xl">
            <span className="block text-darkPurple">
              3 Days of pow-wow Hackathon
            </span>
          </span>
        </h1>
        <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl">
          Let your imagination run wild with our problem statements generated by
          our Sponsors, Govtech. Stand to win attractive prizes.
        </p>
      </div>
      <div className="relative sm:max-w-lg sm:mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-span-8 lg:flex lg:items-center">
        <div className="relative mx-auto w-full lg:max-w-2xl">
          <img src={hero} alt="" />
        </div>
      </div>
    </div>
  );
}
